# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auth',
            field=models.CharField(default='warlock921', max_length=100),
        ),
    ]
